spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    ddl-auto: update
    hibernate:
      generate-ddl: true
      ddl-auto: update
