spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/algarfoodBD
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true